import { Dimensions, StyleSheet } from 'react-native';
import { borderRadius, colors, commonStyles, shadows, spacing, typography } from './designSystem';

const { width } = Dimensions.get('window');

export const produtoDetailStyles = StyleSheet.create({
  container: {
    ...commonStyles.container,
    alignItems: 'flex-end',
  },
  scrollView: {
    flex: 1,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
    padding: spacing.xl,
  },
  loadingText: {
    ...commonStyles.textSecondary,
    marginTop: spacing.sm,
    textAlign: 'right',
  },
  header: {
    padding: spacing.lg,
    backgroundColor: colors.surface,
    ...shadows.sm,
    alignItems: 'flex-end',
  },
  title: {
    ...commonStyles.textHeading,
    fontSize: typography.fontSize['2xl'],
    textAlign: 'right',
  },
  subtitle: {
    ...commonStyles.textSecondary,
    fontSize: typography.fontSize.base,
    marginTop: spacing.xs,
    textAlign: 'right',
  },
  productContainer: {
    padding: spacing.lg,
    alignItems: 'flex-end',
  },
  productImage: {
    width: '100%',
    height: 150,
    borderRadius: borderRadius.xl,
    marginBottom: spacing.lg,
    alignSelf: 'flex-end',
  },
  productInfo: {
    backgroundColor: colors.surface,
    borderRadius: borderRadius.xl,
    padding: spacing.lg,
    marginBottom: spacing.lg,
    ...shadows.md,
    alignItems: 'flex-end',
  },
  productName: {
    ...commonStyles.textHeading,
    fontSize: typography.fontSize.xl,
    marginBottom: spacing.sm,
    textAlign: 'right',
  },
  productPrice: {
    fontSize: typography.fontSize['2xl'],
    fontWeight: typography.fontWeight.bold,
    color: colors.success,
    marginBottom: spacing.md,
    textAlign: 'right',
  },
  productDescription: {
    ...commonStyles.textSecondary,
    fontSize: typography.fontSize.base,
    lineHeight: typography.lineHeight.relaxed * typography.fontSize.base,
    marginBottom: spacing.md,
    textAlign: 'right',
  },
  productCategory: {
    ...commonStyles.textSecondary,
    fontSize: typography.fontSize.sm,
    backgroundColor: colors.surfaceSecondary,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: borderRadius.md,
    alignSelf: 'flex-end',
    textAlign: 'right',
  },
  quantityContainer: {
    backgroundColor: colors.surface,
    borderRadius: borderRadius.xl,
    padding: spacing.lg,
    marginBottom: spacing.lg,
    ...shadows.md,
    alignItems: 'flex-end',
  },
  quantityLabel: {
    ...commonStyles.textPrimary,
    fontSize: typography.fontSize.base,
    fontWeight: typography.fontWeight.semibold,
    marginBottom: spacing.sm,
    textAlign: 'right',
  },
  quantitySelector: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  quantityButton: {
    width: 48,
    height: 48,
    borderRadius: borderRadius.full,
    backgroundColor: colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    ...shadows.sm,
  },
  quantityButtonDisabled: {
    backgroundColor: colors.gray300,
  },
  quantityButtonText: {
    fontSize: typography.fontSize.xl,
    fontWeight: typography.fontWeight.bold,
    color: colors.white,
    textAlign: 'right',
  },
  quantityInput: {
    width: 80,
    height: 48,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: borderRadius.md,
    textAlign: 'right',
    fontSize: typography.fontSize.base,
    fontWeight: typography.fontWeight.semibold,
    marginHorizontal: spacing.md,
    backgroundColor: colors.surfaceSecondary,
  },
  summaryContainer: {
    backgroundColor: colors.surface,
    borderRadius: borderRadius.xl,
    padding: spacing.lg,
    marginBottom: spacing.lg,
    ...shadows.md,
    alignItems: 'flex-end',
  },
  summaryTitle: {
    ...commonStyles.textHeading,
    fontSize: typography.fontSize.lg,
    marginBottom: spacing.md,
    textAlign: 'right',
  },
  summaryRow: {
    flexDirection: 'row-reverse',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.sm,
  },
  summaryLabel: {
    ...commonStyles.textSecondary,
    fontSize: typography.fontSize.base,
    textAlign: 'right',
  },
  summaryValue: {
    ...commonStyles.textPrimary,
    fontSize: typography.fontSize.base,
    fontWeight: typography.fontWeight.semibold,
    textAlign: 'right',
  },
  totalRow: {
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingTop: spacing.sm,
    marginTop: spacing.sm,
  },
  totalLabel: {
    ...commonStyles.textHeading,
    fontSize: typography.fontSize.lg,
    textAlign: 'right',
  },
  totalValue: {
    ...commonStyles.textHeading,
    fontSize: typography.fontSize.lg,
    color: colors.success,
    textAlign: 'right',
  },
  actionsContainer: {
    padding: spacing.lg,
    alignItems: 'flex-end',
  },
  addToCartButton: {
    ...commonStyles.button,
    backgroundColor: colors.primary,
    marginBottom: spacing.md,
    ...shadows.md,
    alignSelf: 'flex-end',
  },
  addToCartButtonText: {
    color: colors.white,
    fontSize: typography.fontSize.lg,
    fontWeight: typography.fontWeight.semibold,
    textAlign: 'right',
  },
  buyNowButton: {
    ...commonStyles.button,
    backgroundColor: colors.success,
    ...shadows.md,
    alignSelf: 'flex-end',
  },
  buyNowButtonText: {
    color: colors.white,
    fontSize: typography.fontSize.lg,
    fontWeight: typography.fontWeight.semibold,
    textAlign: 'right',
  },
  outOfStockContainer: {
    backgroundColor: colors.surface,
    borderRadius: borderRadius.xl,
    padding: spacing.lg,
    alignItems: 'flex-end',
    ...shadows.md,
  },
  outOfStockText: {
    ...commonStyles.textPrimary,
    fontSize: typography.fontSize.lg,
    fontWeight: typography.fontWeight.semibold,
    marginBottom: spacing.md,
    textAlign: 'right',
  },
  notifyButton: {
    ...commonStyles.button,
    backgroundColor: colors.warning,
    ...shadows.sm,
    alignSelf: 'flex-end',
  },
  notifyButtonText: {
    color: colors.white,
    fontSize: typography.fontSize.base,
    fontWeight: typography.fontWeight.semibold,
    textAlign: 'right',
  },
});
